Swifty9/Maverick-AI

.github/workflows/sync-contributors.yml, .gitignore, package-lock.json, package.json, scripts/syncContributors.js, src/App.tsx, src/lib/contributorSync.ts, src/lib/github.ts, src/lib/supabase.ts, src/pages/Contributors.tsx, src/scripts/syncContributors.ts
- New Contributors page with responsive grid layout showing contributor cards
- Automated daily GitHub sync via GitHub Actions workflow
- Supabase integration for storing contributor data
- Role mapping system for team member positions
- Real-time contribution count tracking
- Profile links to GitHub accounts
- Error handling and loading states
The system maintains contributor data through:
- Daily automated syncs at midnight
- Manual trigger option via GitHub Actions
- Persistent storage in Supabase
- Real-time frontend updates when data changes
This feature helps recognize project contributors and maintain an up-to-date record of participation levels, while providing a beautiful UI to showcase team members.
=> feat: Add real-time contributor tracking system

src/pages/team.tsx
=> Added proper style to cards of each member

src/pages/team.tsx
=> added image to center and also proper styling 

src/pages/Contributors.tsx
=> Added proper style to contributors page

src/pages/Contributors.tsx
=> Added Join Us message

src/pages/Home.tsx, src/pages/mission.tsx
=> Added proper Mission Page

src/components/Navbar.tsx, src/pages/global.tsx
=> added global page content

package-lock.json, package.json, src/lib/huggingface.ts, src/lib/moderation.ts
- Integrated HuggingFace emotion analysis model alongside TensorFlow
- Enhanced spam and offensive content pattern detection
- Implemented weighted scoring system
- Added context-aware flagging
- Improved type safety and error handling
=> feat: Enhanced Content Moderation with Dual AI Model Integration

package-lock.json, package.json, src/components/DropdownButton.tsx, src/pages/Results.tsx
Included the jspdf library and a custom dropdown button
=> Fix issue #14 : enables multiple option to download the report

package-lock.json, package.json, src/pages/Home.tsx, src/pages/about.tsx, src/pages/features.tsx, src/pages/global.tsx, src/pages/pricing.tsx, tailwind.config.js
Fixes #58 
This PR introduces a hover effect and smooth animation to the card.
1. Added a scaling effect on hover, where the card increases in size for a more interactive feel.
2. Integrated Framer Motion to add a smooth animation to the card when page is loaded, enhancing the user experience with a visually appealing transition.
Preview :-
https://github.com/user-attachments/assets/af9f83c2-9803-467c-b038-82d470907ce7
=> Add Hover Effect and Animation to Card

package-lock.json, package.json, src/components/DropdownButton.tsx, src/lib/mockHuggingface.ts, src/lib/moderation.ts, src/pages/Results.tsx
- Improved download functionality implementation
- Simplified props structure for better type safety
- Added support for both PDF and JSON download formats
=> fix: resolve DropdownButton type errors and improve download function

src/pages/Home.tsx, src/pages/about.tsx, src/pages/features.tsx
This PR fixes the issue of missing background in the cards.
Before :
After :
=> Added missing Background color of icons in cards

src/components/CopyButton.tsx
Changes Made:
•	Created a CopyButton component:
•	Utilises the Clipboard API for copying text.
•	Displays “Copied!” feedback for 2 seconds after a successful copy.
•	Includes a fallback error message for browsers without Clipboard API support.
•	Ensured the component is accessible and maintains consistent styling using the existing Button component.
Attached are screenshots showing the temporary integration of the button into the “Analyzed Text” section on the Results page. The functionality has been successfully tested.
This feature relates to Issue #11: Add Copy to Clipboard.
=> Feature: Adds copy to clipboard functionality

src/pages/ModerateText.tsx, src/pages/Results.tsx
1. Added support to  edit text after analyzing it
2. Added a clear text button to clear the whole text
=> Fixes #15 : Edit the prompt after analyzing it

src/components/Navbar.tsx
=> Added missing Login Button on Navbar

src/pages/logIn.tsx
=> Commented out Dummy Image Source

src/App.tsx, src/pages/Home.tsx, src/pages/demoTextModeration.tsx
=> Added Demo Page

src/App.tsx, src/pages/Waitlist.tsx, src/pages/about.tsx, src/pages/features.tsx, src/pages/logIn.tsx, src/pages/signUp.tsx
This PR introduces significant improvements to the Waitlist, Login, and Sign-Up pages:
Waitlist Page:
Added a detailed form for user information (name, email, company, role, use case, monthly users). Implemented a professional design with glassmorphism effects and an AI-themed star graphic.
Login and Sign-Up Pages:
Replaced forms with a waitlist overlay, informing users about the private beta and encouraging waitlist sign-up. Maintained consistent design language across the application. These changes aim to enhance user engagement and streamline the onboarding process. Please review the updates.
=> Enhance Waitlist and Authentication Page

README.md
- Add detailed system architecture diagrams using Mermaid
- Include data flow, deployment, and component visualizations
- Document key features and tech stack
- Add installation and setup instructions
- Include API configuration steps
- Update contributing and support information
- Add project maintainer contact details
- Include license and deployment status badges
=> docs: comprehensive README update with system architecture and features

src/components/CountdownTimer.tsx, src/index.css, src/pages/Home.tsx
- Redesigned countdown timer with improved digit animations and spacing
- Added glowing effect to countdown numbers using custom CSS
- Fixed "Learn More" button alignment in Chrome Extension section
=> fix: Enhance UI elements and countdown timer styling

deno.json, src/lib/supabaseClient.ts, src/pages/Waitlist.tsx, src/services/waitlist.ts, src/types/waitlist.ts, supabase/.gitignore, supabase/config.toml
This PR implements a complete waitlist system that allows users to register their interest in the platform.
=> feat: Implement Waitlist System with Supabase Integration

src/index.css, src/pages/Contributors.tsx, src/pages/about.tsx, src/pages/features.tsx, src/pages/logIn.tsx, src/pages/pricing.tsx, src/pages/signUp.tsx
This PR introduces several improvements and enhancements to the UI/UX of the Maverick AI application. Key changes include:
- About Page: Updated the hero section and added new animations for a more engaging user experience.
- Contributors Page: Enhanced the layout and added new motion effects to highlight key sections.
- Features Page: Improved the feature grid and added a call-to-action section to encourage user interaction.
- Pricing Page: Refined the pricing table and added a feature comparison section for better clarity.
- Index.css: Updated styles to support new animations and responsive design elements.
These changes aim to provide a more cohesive and visually appealing experience for users, while also improving accessibility and responsiveness across different devices.
=> Enhance UI/UX across multiple pages and styles
